services:
  update-products-service:
    build: .
    ports:
      - "3008:3008"
    environment:
     SQL_DB_HOST: "${SQL_DB_HOST}"
     SQL_DB_PORT: "${SQL_DB_PORT}"
     SQL_DB_USER: "${SQL_DB_USER}"
     SQL_DB_PASSWORD: "${SQL_DB_PASSWORD}"
     SQL_DB_NAME: "${SQL_DB_NAME}"

    restart: unless-stopped
